# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2v7bHllzoMB_gTq3biDx_Y2SGO60Cco

# Лабораторная работа №1: Исследование двумерного нормального распределения
Выполнил студент гр. 1384 Прошичев Александр. Вариант №12

## Цель работы
Цель:
Исследовать свойства двумерного случайного вектора, имеющего нормальное распределение. \
Овладеть навыками преобразования нормального вектора в стандартный вектор и в вектор с независимыми компонентами.

## Основные теоретические положения
**Определение**: \
Случайный вектор $ \vec{\xi}:\Omega \rightarrow  {\mathbb R}^n$, где $\vec{\xi} = (\xi_1 \dots \xi_n)^T$, называют нормальным (гауссовым), если существует вектор независимых стандартных случайных величин $ \vec{\eta} = (\eta_1 \dots \eta_m)^T$, матрица $A_{n \times m}$, и вещественный вектор $ \vec{B} = (b_1 \dots b_n)^T $, такие что: \
$ \vec{\xi}=A \vec{\eta} + \vec{B} $  
\
Если $ \vec{\xi} \sim \mathcal{N}(\vec{\mu}, \Sigma)$, где $ \vec{\mu} = \mathbb{E} \vec{\xi}$ и $\Sigma = \{cov(\xi_i, \xi_j)\}_{i = 1, j = 1}^n$, тогда плотность невырожденного многомерного нормального распределения будет иметь вид:\
$\rho_{\vec{\xi}}(x_1 \dots x_n) = \frac{1}{(2 \pi)^{n/_2} \sqrt{det \Sigma}} \exp(-\frac{1}{2} (\vec{x} - \vec{\mu})^T \Sigma^{-1} (\vec{x} - \vec{\mu}))$, где $ \vec{x} = (x_1 \dots x_n)^T $
\
\
**Свойства:**
1) Линейная комбинация случайных переменных, пренадлежащих многомерному нормальному распределению, также является нормально распределённой.
2) Условные и безусловные распределения, полученные из многомерного нормального распределения, также являются нормальными распределениями.
3) Параметры многомерного нормального распределения польностью описывают его форму.
4) Многомерное нормальное распределение устойчиво относительно линейных преобразования
Если $\vec{\xi} \sim \mathcal{N}(\vec{\mu}, \Sigma)$, то $ A \vec{\xi} + \vec{B} \sim \mathcal{N}(A \vec{\mu} + \vec{B}, A \Sigma A^T) $

## Постановка задачи
Плотность нормального распределения имеет вид:\
$\rho_{\xi, \eta}(x, y)=C \cdot \exp(-\frac{1}{2}(6x^2+4xy+9y^2+8x-14y+11)) $ /
1. Вычислить вектор математических ожиданий и ковариационные характеристики данного случайного вектора. Построить график плотности распределения $ \rho_{\xi, \eta} $.
2. Найти аффинное преобразование, переводящее исходный случайный вектор в стандартный нормальный.
3. Найти ортогональное преобразование, переводящее соответствующий центрированный случайный вектор в вектор с независимыми компонентами. Построить график плотности полученного распределения.
4. Вычислить характеристики совместного распределения случайного вектора
$ (-2 \xi + 2 \eta, 3 \xi + 4 \eta)^T $ и записать его плотность. Построить график плотности полученного распределения.
5. Найти условные распределения $\xi$ при условии $\eta$.
Вычислить $\mathbb{E}(\xi | \eta) $ и $ \mathbb{D}(\xi | \eta)$.

Перед выполнение работы подключим необходимые библиотеки.
"""

from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt

"""## Выполнение работы
### **1 задание**. Вычислить вектор математических ожиданий и ковариационные характеристики данного случайного вектора. Построить график плотности распределения $ \rho_{\xi, \eta} $.
$\rho_{\xi, \eta}(x, y)=C \cdot \exp(-\frac{1}{2}(6x^2+4xy+9y^2+8x-14y+11)) $
\
\
Приведём квадратичную форму к каноническому виду. \
$ \sqsupset \varphi(x, y) = 6x^2+4xy+9y^2+8x-14y+11= (6x^2+4xy+8x) + 9y^2 - 14y + 11 = 2(3x^2 + 2x(y + 2)) + 9y^2 - 14y + 11 = 6(x^2 + 2x (\frac{y}{3} + \frac{2}{3})) + 9y^2 - 14y + 11 = 6(x^2 + 2x (\frac{y}{3} + \frac{2}{3}) + (\frac{y}{3} + \frac{2}{3})^2 - (\frac{y}{3} + \frac{2}{3})^2) + 9y^2 - 14y + 11 = 6(x + \frac{y}{3} + \frac{2}{3})^2 - 6(\frac{y}{3} + \frac{2}{3})^2 + 9y^2 - 14y + 11 = 6(x + \frac{y}{3} + \frac{2}{3})^2 - \frac{2y^2}{3} - \frac{8y}{3} - \frac{8}{3} + 9y^2 - 14y + 11 = 6(x + \frac{y}{3} + \frac{2}{3})^2 + \frac{25y^2}{3} - \frac{50y}{3} + \frac{25}{3} = 6(x + \frac{y}{3} + \frac{2}{3})^2 + \frac{25}{3}(y^2 - 2y + 1) = \mathbf{6(x + \frac{y}{3} + \frac{2}{3})^2 + \frac{25}{3}(y - 1)^2} = 6(x + \frac{1}{3}(y - 1 + 3))^2 + \frac{25}{3}(y - 1)^2 = 6((x + 1) + \frac{1}{3}(y - 1))^2 + \frac{25}{3}(y - 1)^2 = 6((x + 1)^2 + \frac{2}{3}(x + 1)(y - 1) + \frac{1}{9}(y - 1)^2) + \frac{25}{3}(y - 1)^2 = 6(x+1)^2 + 4(x + 1)(y - 1) + \frac{2}{3}(y - 1)^2 + \frac{25}{3}(y - 1)^2 = \mathbf{6(x+1)^2 + 4(x + 1)(y - 1) + 9(y - 1)^2}$
\
\
По каноническому виду мы можем найти мат. ожидание $\mathbb{E}\vec{\xi}$ и матрицу ковариаций $ \Sigma $. \
$\mathbb{E} \begin{pmatrix} \xi \\ \eta \end{pmatrix} = \begin{pmatrix} -1 \\ 1 \end{pmatrix} \quad \Sigma^{-1} = \begin{pmatrix} 6 & 2 \\ 2 & 9 \end{pmatrix} \quad det \Sigma^{-1} = 54 - 4 = 50 \implies \Sigma = \frac{1}{50} \begin{pmatrix} 9 & -2 \\ -2 & 6 \end{pmatrix}$ \
\
Найдём ковариационные характеристики данного случайного вектора
$ cov(\xi, \eta) = -\frac{1}{25} \quad \mathbb{D}_{\xi} = \frac{9}{50}  \quad \mathbb{D}_{\eta} = \frac{3}{25} \implies \rho(\xi, \eta)=\frac{cov({\xi},{ \eta})}{\sqrt{\mathbb{D}_{\xi} \mathbb{D}_{\eta}}} = \frac{-\frac{1}{25}}{\sqrt{\frac{9}{50} \frac{3}{25}}} = -\frac{25}{25} \frac{1}{\sqrt{\frac{27}{2}}} = -\frac{\sqrt{2}}{3 \sqrt{3}}$ \
\
Найдём коэффициент плотности распределения $C$. \
$C = \frac{1}{(2 \pi)^{\frac{n}{2}} \sqrt{det \Sigma}} = \frac{1}{2 \pi \sqrt{\frac{1}{50}}} = \frac{5 \sqrt{2}}{2 \pi}=\frac{5}{\pi \sqrt{2}}$ \
\
Тогда функция плотности выглядит следующим образом \
$\rho_{\xi, \eta}(x, y)= \frac{5}{\pi \sqrt{2}} \cdot \exp(-\frac{1}{2}(6x^2+4xy+9y^2+8x-14y+11)) $


"""

def p(x, y):
    return (5 / (np.pi * np.sqrt(2))) * np.exp(-0.5 * (6 * x ** 2 + 4 * x * y + 9 * y ** 2 + 8 * x - 14 * y + 11))


x = np.linspace(-3, 1, 200)
y = np.linspace(-3, 5, 200)

X, Y = np.meshgrid(x, y)
Z = p(X, Y)

fig = plt.figure(figsize=(10,8))
ax = plt.axes(projection='3d')

ax.plot_surface(X, Y, Z, cmap='OrRd')
ax.set_title('График функции плотности')
ax.set_xlabel('x', fontsize=12)
ax.set_ylabel('y', fontsize=12)
ax.set_zlabel('z', fontsize=12)
plt.show()

"""### **2 задание**. Найти аффинное преобразование, переводящее исходный случайный вектор в стандартный нормальный.
Согласно свойству №4 подберём такие $A$ и $\vec{B}$, что $ A \vec{\xi} + \vec{B} \sim \mathcal{N}(0, 1) $. Рассмотрим квадратичную форму в следующем виде \
$\varphi(x, y) = 6(x + \frac{y}{3} + \frac{2}{3})^2 + \frac{25}{3}(y - 1)^2 = (\sqrt{6}x + \frac{\sqrt{2}y}{\sqrt{3}} + \frac{2 \sqrt{2}}{\sqrt{3}})^2 + (\frac{5y}{\sqrt{3}} - \frac{5}{\sqrt{3}})^2$ \
\
$\sphericalangle \quad A = \begin{pmatrix} \sqrt{6} & \frac{\sqrt{2}}{\sqrt{3}}  \\ 0 & \frac{5}{\sqrt{3}} \end{pmatrix} \quad \vec{B} = \begin{pmatrix} \frac{2 \sqrt{2}}{\sqrt{3}}  \\ - \frac{5}{\sqrt{3}} \end{pmatrix}$
Тогда $ \begin{pmatrix} \xi_{st}  \\ \eta_{st} \end{pmatrix} = \begin{pmatrix} \sqrt{6} & \frac{\sqrt{2}}{\sqrt{3}}  \\ 0 & \frac{5}{\sqrt{3}} \end{pmatrix} \begin{pmatrix} \xi \\ \eta \end{pmatrix} + \begin{pmatrix} \frac{2 \sqrt{2}}{\sqrt{3}}  \\ - \frac{5}{\sqrt{3}} \end{pmatrix} $ \
\
Проверим вектор на стандартную нормальную форму. $ \mathbb{E} \begin{pmatrix} \xi_{st}  \\ \eta_{st} \end{pmatrix} = \begin{pmatrix} \sqrt{6} & \frac{\sqrt{2}}{\sqrt{3}}  \\ 0 & \frac{5}{\sqrt{3}} \end{pmatrix} \begin{pmatrix} -1\\ 1 \end{pmatrix} + \begin{pmatrix} \frac{2 \sqrt{2}}{\sqrt{3}}  \\ - \frac{5}{\sqrt{3}} \end{pmatrix} = \begin{pmatrix} - \sqrt{6} + \frac{\sqrt{2}}{\sqrt{3}}  \\ 0 + \frac{5}{\sqrt{3}} \end{pmatrix} + \begin{pmatrix} \frac{2 \sqrt{2}}{\sqrt{3}}  \\ - \frac{5}{\sqrt{3}} \end{pmatrix} = \begin{pmatrix} - \frac{2 \sqrt{2}}{\sqrt{3}}  \\ \frac{5}{\sqrt{3}} \end {pmatrix} + \begin{pmatrix} \frac{2 \sqrt{2}}{\sqrt{3}}  \\ - \frac{5}{\sqrt{3}} \end{pmatrix} = 0 $ \
$ \Sigma_{st} = A \Sigma A^T = \begin{pmatrix} \sqrt{6} & \frac{\sqrt{2}}{\sqrt{3}}  \\ 0 & \frac{5}{\sqrt{3}} \end{pmatrix} \begin{pmatrix} \frac{9}{50} & - \frac{2}{50}  \\ - \frac{2}{50} & \frac{6}{50} \end{pmatrix} \begin{pmatrix} \sqrt{6} & 0  \\ \frac{\sqrt{2}}{\sqrt{3}} & \frac{5}{\sqrt{3}} \end{pmatrix} = \frac{1}{150} \begin{pmatrix} 3\sqrt{2} & \sqrt{2}  \\ 0 & 5 \end{pmatrix} \begin {pmatrix} 9 & -2  \\ -2 & 6 \end{pmatrix} \begin{pmatrix} 3\sqrt{2} & 0  \\ \sqrt{2} & 5 \end{pmatrix} = \frac{1}{150} \begin{pmatrix} 25\sqrt{2} & 0  \\ -10 & 30 \end{pmatrix} \begin{pmatrix} 3\sqrt{2} & 0  \\ \sqrt{2} & 5 \end{pmatrix} = \frac{1}{150} \begin{pmatrix} 150 & 0  \\ 0 & 150 \end{pmatrix} = E $ \
\
Таким образом, $ A \vec{\xi} + \vec{B} \sim \mathcal{N}(0, 1) $, а значит аффинное преобразование было найдено.

### **3 задание**. Найти ортогональное преобразование, переводящее соответствующий центрированный случайный вектор в вектор с независимыми компонентами. Построить график плотности полученного распределения.
Для получение ортогонального преобразования найдём собственные числа матрицы $\Sigma^{-1}$ с помощью уравнения $\lambda^2 - th( \Sigma^{-1} ) + det( \Sigma^{-1} ) = 0$. \
$ th(\Sigma^{-1}) = 15 \quad det(\Sigma^{-1}) = 50 \implies \lambda^2 - 15 \lambda + 50 = 0$ \
$ \mathcal{D} = 225 - 200 = 5^2$ \
$\lambda_1 = \frac{15 - 5}{2} = 5$ \
$\lambda_2 = \frac{15 + 5}{2} = 10$ \
\
При $ \lambda = 5 $\
$
\begin{pmatrix}
1 & 2  \\
2 & 4
\end{pmatrix}
\begin{pmatrix}
q_{11}   \\
q_{12}
\end{pmatrix} = 0
\implies
q_1= \frac{1}{\sqrt{5}}
\begin{pmatrix}
2  \\
-1
\end{pmatrix}
$ \
\
При $ \lambda = 10 $\
$
\begin{pmatrix}
-4 & 2  \\
2 & 1
\end{pmatrix}
\begin{pmatrix}
q_{21}   \\
q_{22}
\end{pmatrix} = 0
\implies
q_2= \frac{1}{\sqrt{5}}
\begin{pmatrix}
1  \\
2
\end{pmatrix}
$ \
\
$Q^T = \frac{1}{\sqrt{5}}
\begin{pmatrix}
2 & 1   \\
-1 & 2
\end{pmatrix} \implies Q =
\begin{pmatrix}
2 & -1   \\
1 & 2
\end{pmatrix}
$ \
\
Найдём $\mathbb{E} \vec{\xi_{ort}} $ и $\Sigma_{ort} $. \
$ \mathbb{E}
\begin{pmatrix}
\xi_{ort}   \\
\eta_{ort}
\end{pmatrix}  = \frac{1}{\sqrt{5}}
\begin{pmatrix}
2 & -1   \\
1 & 2
\end{pmatrix}
\begin{pmatrix}
-1   \\
1
\end{pmatrix} = \frac{1}{\sqrt{5}}
\begin{pmatrix}
-3   \\
1
\end{pmatrix}
$ \
\
$ \Sigma_{ort}=Q \Sigma Q^T = \frac{1}{250}
\begin{pmatrix}
2 & -1   \\
1 & 2
\end{pmatrix}
\begin{pmatrix}
9 & -2   \\
-2 & 6
\end{pmatrix}
\begin{pmatrix}
2 & 1   \\
-1 & 2
\end{pmatrix} =  \frac{1}{250}
\begin{pmatrix}
20 & -10   \\
5 & 10
\end{pmatrix}
\begin{pmatrix}
2 & 1   \\
-1 & 2
\end{pmatrix} = \frac{1}{250}
\begin{pmatrix}
50 & 0   \\
0 & 25
\end{pmatrix} =
\begin{pmatrix}
\frac{1}{5} & 0   \\
0 & \frac{1}{10}
\end{pmatrix}
$ \

Заметим, что $\Sigma_{ort}^{-1} =
\begin{pmatrix}
\lambda_1 = 5 & 0   \\
0 & \lambda_2 = 10
\end{pmatrix} $,  вследствие чего полученное преобразование можно считать корректным. \
\
Найдём коэффициент $C$ функции плотности распределения. \
$C = \frac{1}{(2 \pi)^{\frac{n}{2}} \sqrt{det \Sigma_{ort}}} = \frac{1}{2 \pi \sqrt{\frac{1}{50}}} = \frac{5 \sqrt{2}}{2 \pi}=\frac{5}{\pi \sqrt{2}}$ \
\
Тогда функция плотности распределения будет выглядеть следующим образом \
$\rho_{\xi_{ort}, \eta_{ort}}(x, y)= \frac{5}{\pi \sqrt{2}} \cdot \exp(-\frac{1}{2}(5x^2 + 10y^2 + 6 \sqrt{5}x - 4 \sqrt{5}y + 11)) $
"""

def p(x, y):
    return (5 / (np.pi * np.sqrt(2))) * np.exp(-0.5 * (5*x ** 2 + 10 * y ** 2 + 6 * np.sqrt(5) * x - 4 * np.sqrt(5) * y + 11 ))


x = np.linspace(-3, 0, 200)
y = np.linspace(-2, 3, 200)

X, Y = np.meshgrid(x, y)
Z = p(X, Y)

fig = plt.figure(figsize=(10,8))
ax = plt.axes(projection='3d')

ax.plot_surface(X, Y, Z, cmap='OrRd')
ax.set_title('График функции плотности')
ax.set_xlabel('x', fontsize=12)
ax.set_ylabel('y', fontsize=12)
ax.set_zlabel('z', fontsize=12)
plt.show()

"""\

### **4 задание**. Вычислить характеристики совместного распределения случайного вектора $ (-2 \xi + 2 \eta, 3 \xi + 4 \eta)^T $ и записать его плотность. Построить график плотности полученного распределения.

Представим новой вектор, как линейное преобразование известного $ \vec{\xi}$:
$ \vec{\xi_н} = A \vec{\xi} + \vec{B}$ \
$ \vec{\xi_н} =
\begin{pmatrix}
-2 \xi + 2 \eta  \\
3 \xi + 4 \eta
\end{pmatrix} =
\begin{pmatrix}
-2 & 2  \\
3 & 4
\end{pmatrix}
\begin{pmatrix}
\xi   \\
\eta
\end{pmatrix} +
\begin{pmatrix}
0   \\
0
\end{pmatrix}
$ \
\
Найдём $\mathbb{E} \vec{\xi_{н}} $ и $\Sigma_{н} $. \
$ \mathbb{E}
\begin{pmatrix}
\xi_{н}   \\
\eta_{н}
\end{pmatrix}  =
\begin{pmatrix}
-2 & 2   \\
3 & 4
\end{pmatrix}
\begin{pmatrix}
-1   \\
1
\end{pmatrix} =
\begin{pmatrix}
4   \\
1
\end{pmatrix}
$ \
\
$ \Sigma_{н}=A \Sigma A^T = \frac{1}{50}
\begin{pmatrix}
-2 & 2   \\
3 & 4
\end{pmatrix}
\begin{pmatrix}
9 & -2   \\
-2 & 6
\end{pmatrix}
\begin{pmatrix}
-2 & 3   \\
2 & 4
\end{pmatrix} =  \frac{1}{50}
\begin{pmatrix}
-22 & 16   \\
19 & 18
\end{pmatrix}
\begin{pmatrix}
-2 & 3   \\
2 & 4
\end{pmatrix} = \frac{1}{50}
\begin{pmatrix}
76 & -2   \\
-2 & 129
\end{pmatrix} $ \
$det \Sigma_н = \frac{76 \times 129}{50^2} - \frac{4}{50^2} = \frac{196}{50} \implies \Sigma^{-1}_н = \frac{1}{196}
\begin{pmatrix}
129 & 2   \\
2 & 76
\end{pmatrix} $ \
\
Найдём характеристики совместного распределения. \
$ cov(\xi_н, \eta_н) = -\frac{1}{25} \quad \mathbb{D}_{\xi_н} = \frac{38}{25} \quad \mathbb{D}_{\eta_н} = \frac{129}{50} \implies \rho(\xi_н, \eta_н)=\frac{cov({\xi_н},{ \eta_н})}{\sqrt{\mathbb{D}_{\xi} \mathbb{D}_{\eta}}} = \frac{-\frac{1}{25}}{\sqrt{\frac{76}{50} \frac{129}{25}}} = -\frac{50}{25} \frac{1}{2 \sqrt{2451}} = -\frac{1}{\sqrt{2451}}$ \
\
Найдём коэффициент плотности распределения $C$. \
$C = \frac{1}{(2 \pi)^{\frac{n}{2}} \sqrt{det \Sigma_н}} = \frac{1}{2 \pi \frac{7 \sqrt{2}}{5}} = \frac{5}{14 \sqrt{2} \pi}$ \
\
Тогда функция плотности выглядит следующим образом \
$\rho_{\xi_н, \eta_н}(x, y)= \frac{5}{14 \sqrt{2} \pi} \cdot \exp(-\frac{1}{392}(129x^2+4xy+76y^2-1036x-168y+2156)) $
"""

def p(x, y):
    return (5 / (14 * np.pi * np.sqrt(2))) * np.exp(-0.5 * (129 * x ** 2 + 4 * x * y + 76 * y ** 2 - 1036 * x - 168 * y + 2156 ) / 196)


x = np.linspace(-3, 10, 200)
y = np.linspace(-3, 3, 200)

X, Y = np.meshgrid(x, y)
Z = p(X, Y)

fig = plt.figure(figsize=(10,8))
ax = plt.axes(projection='3d')

ax.plot_surface(X, Y, Z, cmap='OrRd')
ax.set_title('График функции плотности')
ax.set_xlabel('x', fontsize=12)
ax.set_ylabel('y', fontsize=12)
ax.set_zlabel('z', fontsize=12)
plt.show()

"""\

### **5 задание**. Найти условные распределения $\xi$ при условии $\eta$. Вычислить $\mathbb{E}(\xi | \eta) $ и $ \mathbb{D}(\xi | \eta)$.

Из п. №1 $\mathbb{E}_{\eta} = 1 \quad \mathbb{D}_{\eta}=\frac{3}{25}$. Следовательно, составим плотность по $\eta$ по общей формуле \
$\rho_{\eta}(y)=\frac{1}{\sqrt{2 \pi \mathbb{D}_{\eta}}} \exp(-\frac{1}{2} \frac{(y - a_{\eta})^2}{\mathbb{D}_{\eta}}) = \frac{5}{\sqrt{6 \pi}} \exp(-\frac{1}{2} \frac{25}{3}(y - 1)^2) = \frac{5}{\sqrt{6 \pi}} \exp(-\frac{1}{2} \varphi'(y)) $ \
\
По формуле условной плотности распределения \

$\rho_{\xi | \eta  = y}(x) = \frac{\rho_{\xi, \eta}(x, y)}{\rho_{\eta}(y)} = \frac{5}{\pi \sqrt{2}} \frac{\sqrt{6 \pi}}{5} \exp (- \frac{1}{2} ( \varphi(x, y) - \varphi'(y))) $ \
$ \varphi(x, y) - \varphi(y) = 6(x + 1)^2 + 4(x + 1)(y - 1) + 9(y - 1)^2 - \frac{25}{3}(y - 1)^2 = 6(x + 1)^2 + 4(x + 1)(y - 1) + \frac{2}{3}(y - 1)^2 = 6x^2 + 12x + 6 + 4xy - 4x + 4y - 4 + \frac{2y^2}{3} - \frac{4y}{3} + \frac{2}{3} = 6x^2 + 8x + 4xy + \frac{2y^2}{3} + \frac{8y}{3} + \frac{8}{3} = 6(x^2 + \frac{2xy}{3} + \frac{4x}{3}) + \frac{2y^2}{3} + \frac{8y}{3} + \frac{8}{3} = 6 (x^2 + 2x(\frac{y}{3} + \frac{2}{3}) + (\frac{y}{3} - \frac{2}{3})^2 - (\frac{y}{3} - \frac{2}{3})^2) + \frac{2y^2}{3} + \frac{8y}{3} + \frac{8}{3} = 6(x + \frac{y}{3} + \frac{2}{3})^2 - 6 (\frac{y^2}{9} + \frac{4y}{9} + \frac{4}{9}) + \frac{2y^2}{3} + \frac{8y}{3} + \frac{8}{3} = 6(x + \frac{y}{3} + \frac{2}{3})^2$ \
\
Таким образом, можно сделать вывод, что $\mathbb{E}_{\xi | \eta = y}(x) = - \frac{1}{3} (y + 2)$ и $\mathbb{D}_{\xi | \eta = y}(x) = \frac{1}{6} $

## Выводы

В ходе данной лабораторной работы были исследованы свойства двумерного случайного вектора, имеющего нормальное распределение, также приобретены навыки преобразования нормального вектора в стандартный и в вектор с независимыми компонентами.Вычислен вектор математических ожиданий и ковариационных характеристик для данного случайного вектора, найдено аффинное преобразование, переводящее исходный случайный вектор в стандартный нормальный, найдено ортогональное преобразование, переводящее соответствующий центрированный случайный вектор в вектор с независимыми компонентами, вычислены характеристики совместного распределения случайного вектора, а также найдено условное распределение и соответствующие ему характеристики.
"""